RANDOM_SEED: 0
AMP: true
CUDNN_BENCHMARK: true
CUDNN_DETERMINISTIC: false

DATA:
  ROOT: "datasets/inaturalist"
  IMAGE_TRANSFORM_TRAIN:
    - "random_resized_crop::{'scale': (0.08, 1.0)}"
    - "horizontal_flip"
    - "normalize"
  IMAGE_TRANSFORM_VAL:
    - "smallest_resize"
    - "center_crop"
    - "normalize"

MODEL:
  VISUAL:
    FROZEN: false
    
OPTIM:
  BATCH_SIZE: 256
  SGD_MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  NO_DECAY: "none"
  LOOKAHEAD:
    USE: false

  LR: 0.025
  WARMUP_STEPS: 0
  LR_DECAY_NAME: multistep
  LR_GAMMA: 0.1
  LR_STEPS:
    - 119700  # 70 epochs
    - 153900  # 90 epochs
  NUM_ITERATIONS: 171000  # 100 epochs
